In [5]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
import tempfile
from devkit.dataset import fetch_file, unzip_to_data_subdir, get_subdir_files_as_dict
temp_dir = tempfile.gettempdir()
temp_zip_path = tempfile.mktemp(suffix=".zip", dir=temp_dir)
url = "https://github.com/bowang-lab/AGILE/raw/81900a160f60f8d0728896d347fe569c952d6bd9/data.zip"
fetch_file(url,temp_zip_path)
unzip_to_data_subdir(temp_zip_path,'LNP_AGILE')
data = get_subdir_files_as_dict('LNP_AGILE')
data

https://github.com/bowang-lab/AGILE/raw/81900a160f60f8d0728896d347fe569c952d6bd9/data.zip -> 'C:\\Users\\ntrus\\AppData\\Local\\Temp\\tmp7ffjdr5z.zip'


  0%|          | 0.00/52.1M [00:00<?, ?iB/s]

{'candidate_set_smiles_plus_features.csv': 'F:\\data\\LNP_AGILE\\data\\candidate_set_smiles_plus_features.csv',
 'finetuning_set_smiles_plus_features.csv': 'F:\\data\\LNP_AGILE\\data\\finetuning_set_smiles_plus_features.csv',
 '._candidate_set_smiles_plus_features.csv': 'F:\\data\\LNP_AGILE\\__MACOSX\\data\\._candidate_set_smiles_plus_features.csv',
 '._finetuning_set_smiles_plus_features.csv': 'F:\\data\\LNP_AGILE\\__MACOSX\\data\\._finetuning_set_smiles_plus_features.csv'}

In [7]:
import pandas as pd
df = pd.read_csv(data['finetuning_set_smiles_plus_features.csv'])
can_df = pd.read_csv(data['candidate_set_smiles_plus_features.csv'])
df

smiles  expt_Hela  expt_Raw  \
0     CCCCCCCC\C=C/CCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCC...   0.475362 -0.943598   
1     CCCCCCCCCCCCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCCC\C...   0.069628 -0.471743   
2     CCCCCCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCCC\C=C/CCC...   3.245195  5.423429   
3     CCCCCCCCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCCC\C=C/C...   2.508357  2.310532   
4     CCCCCCCCCCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCCC\C=C...   5.427294  0.771155   
...                                                 ...        ...       ...   
1195  CCCCCCCC\C=C/CCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCC...   6.501837  1.705982   
1196  CCCCCCCCCCCCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCCCCC...   6.142469 -0.891244   
1197  CCCCCCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCCCCC=C)NCC...   8.177133  2.918444   
1198  CCCCCCCCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCCCCC=C)N...  -0.080869 -0.544540   
1199  CCCCCCCCCCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCCCCC=C...   6.261474  3.792084   

      desc_ABC/10  desc_ABCGG/10  desc_nBase  desc_SpAbs_A/30  desc_SpMax_A  \
0        3.988571       2.490832         3.0         2.365406      2.200338   
1        3.988571       2.490832         3.0         2.365406      2.200338   
2        3.564307       2.337770         3.0         2.110146      2.200337   
3        3.705728       2.390907         3.0         2.195279      2.200338   
4        3.847150       2.441808         3.0         2.280361      2.200338   
...           ...            ...         ...              ...           ...   
1195     3.518325       2.407701         2.0         2.039306      2.233648   
1196     3.518325       2.407701         2.0         2.039306      2.233648   
1197     3.094061       2.246607         2.0         1.784046      2.233648   
1198     3.235482       2.302550         2.0         1.869178      2.233648   
1199     3.376904       2.356126         2.0         1.954260      2.233648   

      desc_SpDiam_A  desc_SpAD_A/30  ...  desc_SRW08  desc_SRW09  desc_SRW10  \
0          4.400676        2.365406  ...    8.440096         0.0    9.809891   
1          4.400676        2.365406  ...    8.440096         0.0    9.809891   
2          4.400675        2.110146  ...    8.344980         0.0    9.723224   
3          4.400676        2.195279  ...    8.377701         0.0    9.752955   
4          4.400676        2.280361  ...    8.409385         0.0    9.781828   
...             ...             ...  ...         ...         ...         ...   
1195       4.467296        2.039306  ...    8.427487         0.0    9.852142   
1196       4.467296        2.039306  ...    8.427487         0.0    9.852142   
1197       4.467296        1.784046  ...    8.331105         0.0    9.769213   
1198       4.467296        1.869178  ...    8.364275         0.0    9.797627   
1199       4.467296        1.954260  ...    8.396381         0.0    9.825256   

      desc_MW/100  desc_AMW  desc_WPath/10000  desc_WPol/10  desc_Zagreb1/100  \
0        8.027639  5.179122            2.4072           6.0              2.30   
1        8.047795  5.125984            2.4072           6.0              2.30   
2        7.206856  5.184789            1.7158           5.4              2.06   
3        7.487169  5.163565            1.9248           5.6              2.14   
4        7.767482  5.144028            2.1550           5.8              2.22   
...           ...       ...               ...           ...               ...   
1195     7.036591  5.212290            1.5633           5.6              2.06   
1196     7.056747  5.150911            1.5633           5.6              2.06   
1197     6.215808  5.223368            1.0378           5.0              1.82   
1198     6.496121  5.196897            1.1943           5.2              1.90   
1199     6.776434  5.172851            1.3692           5.4              1.98   

      desc_Zagreb2/100  desc_mZagreb2/10  
0                 2.34          1.427778  
1                 2.34          1.427778  
2                 2.10          1.277778  
3                 2.18          1

In [12]:
from devkit.utils import tqdm_imap
import numpy as np
import pandas as pd
import umap
from rdkit import Chem
from rdkit.Chem import AllChem, DataStructs
import matplotlib.pyplot as plt
import math
import torch
import gpytorch
from matplotlib import pyplot as plt
import torch
from botorch.models import SingleTaskGP
from gpytorch.kernels import Kernel
from gpytorch.kernels.scale_kernel import ScaleKernel
from gpytorch.distributions.multivariate_normal import MultivariateNormal
from sklearn.model_selection import train_test_split

def smi_to_fingerprint(smiles,radius=2, nBits=2048):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius, nBits=nBits)
        arr = np.zeros((1,), dtype=np.uint8)
        DataStructs.ConvertToNumpyArray(fp, arr)
        return arr
    else:
        return None

In [9]:
fingerprints = tqdm_imap(df.smiles.to_list(),smi_to_fingerprint,n_procs=1)
df['morgan_fp'] = fingerprints

Serial f=smi_to_fingerprint:   0%|          | 0/1200 [00:00<?, ?it/s]

In [10]:
df.head()

smiles  expt_Hela  expt_Raw  \
0  CCCCCCCC\C=C/CCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCC...   0.475362 -0.943598   
1  CCCCCCCCCCCCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCCC\C...   0.069628 -0.471743   
2  CCCCCCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCCC\C=C/CCC...   3.245195  5.423429   
3  CCCCCCCCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCCC\C=C/C...   2.508357  2.310532   
4  CCCCCCCCCCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCCC\C=C...   5.427294  0.771155   

   desc_ABC/10  desc_ABCGG/10  desc_nBase  desc_SpAbs_A/30  desc_SpMax_A  \
0     3.988571       2.490832         3.0         2.365406      2.200338   
1     3.988571       2.490832         3.0         2.365406      2.200338   
2     3.564307       2.337770         3.0         2.110146      2.200337   
3     3.705728       2.390907         3.0         2.195279      2.200338   
4     3.847150       2.441808         3.0         2.280361      2.200338   

   desc_SpDiam_A  desc_SpAD_A/30  ...  desc_SRW09  desc_SRW10  desc_MW/100  \
0       4.400676        2.365406  ...         0.0    9.809891     8.027639   
1       4.400676        2.365406  ...         0.0    9.809891     8.047795   
2       4.400675        2.110146  ...         0.0    9.723224     7.206856   
3       4.400676        2.195279  ...         0.0    9.752955     7.487169   
4       4.400676        2.280361  ...         0.0    9.781828     7.767482   

   desc_AMW  desc_WPath/10000  desc_WPol/10  desc_Zagreb1/100  \
0  5.179122            2.4072           6.0              2.30   
1  5.125984            2.4072           6.0              2.30   
2  5.184789            1.7158           5.4              2.06   
3  5.163565            1.9248           5.6              2.14   
4  5.144028            2.1550           5.8              2.22   

   desc_Zagreb2/100  desc_mZagreb2/10  \
0              2.34          1.427778   
1              2.34          1.427778   
2              2.10          1.277778   
3              2.18          1.327778   
4              2.26          1.377778   

                                           morgan_fp  
0  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  
1  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  
2  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  
3  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  
4  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...  

[5 rows x 817 columns]

In [13]:
y = df['expt_Hela'].to_numpy()
X = np.vstack(df['morgan_fp'].to_list())
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = torch.tensor(X_train).double()
X_test = torch.tensor(X_test).double()
y_train = torch.tensor(y_train).double()
y_test = torch.tensor(y_test).double()
X_train.dim(),X_test.dim(),y_train.dim()

(2, 2, 1)

In [14]:
X_test,X_train,y_train,y_test

(tensor([[0., 1., 1.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 1., 1.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.]], dtype=torch.float64),
 tensor([[0., 1., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 1., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.]], dtype=torch.float64),
 tensor([ 7.3466e+00,  8.1873e-01,  3.0482e-01,  7.5050e+00,  1.0020e+00,
          4.6565e+00,  1.5100e+00,  7.4190e+00,  4.7993e-01,  2.9523e+00,
          7.9996e-01,  5.8478e+00,  5.5398e+00,  2.7007e+00,  4.4703e+00,
          5.6291e+00,  1.5317e+00,  1.1901e+00,  6.6852e+00,  5.3890e+00,
          7.0214e+00,  4.4211e+00,  1.6712e+00,  3.0706e+00,  9.4249e+00,
          6.2564e+00,  4.5834e+00,  6.8632e+00,  4.4018e-01,  7.

In [15]:


class TanimotoKernel(Kernel):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        #self.register_parameter(name="lengthscale", parameter=torch.tensor(1.0))

    def forward(self, x1, x2, **params):
        x1_norm = x1.norm(dim=-1)
        x2_norm = x2.norm(dim=-1)
        numerator = torch.einsum("bi,bj->bij", x1, x2)
        denominator = x1_norm.unsqueeze(-1) * x2_norm.unsqueeze(-2) + 1e-8
        return torch.exp(-self.lengthscale * (1 - numerator / denominator))

# We will use the simplest form of GP model, exact inference
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        #self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())
        self.covar_module = gpytorch.kernels.ScaleKernel(TanimotoKernel())

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

# initialize likelihood and model
likelihood = gpytorch.likelihoods.GaussianLikelihood()
model = ExactGPModel(X_train, y_train, likelihood)

In [16]:
# this is for running the notebook in our testing framework
training_iter = 50

# Find optimal model hyperparameters
model.train()
likelihood.train()

# Use the adam optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)  # Includes GaussianLikelihood parameters

# "Loss" for GPs - the marginal log likelihood
mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

for i in range(training_iter):
    # Zero gradients from previous iteration
    optimizer.zero_grad()
    # Output from model
    output = model(X_train)
    # Calc loss and backprop gradients
    loss = -mll(output, y_train)
    loss.backward()
    print('Iter %d/%d - Loss: %.3f   lengthscale: %.3f   noise: %.3f' % (
        i + 1, training_iter, loss.item(),
        model.covar_module.base_kernel.lengthscale.item(),
        model.likelihood.noise.item()
    ))
    optimizer.step()

RuntimeError: [enforce fail at alloc_cpu.cpp:80] data. DefaultCPUAllocator: not enough memory: you tried to allocate 32212254720 bytes.

In [ ]:
# Get into evaluation (predictive posterior) mode
model.eval()
likelihood.eval()

# Test points are regularly spaced along [0,1]
# Make predictions by feeding model through likelihood
with torch.no_grad(), gpytorch.settings.fast_pred_var():
    g = model(X_test)
    observed_pred = likelihood(g)
observed_pred

RuntimeError: einsum(): subscript b has size 1200 for operand 1 which does not broadcast with previously seen size 240

In [ ]:
with torch.no_grad():
    # Get upper and lower confidence bounds
    lower, upper = observed_pred.confidence_region()
    mean = observed_pred.mean.numpy()

for l,u,m in zip(lower,upper,mean):
    print(f"{l:0.02f} {m:0.02f} {u:0.02f}")

2.20 5.83 9.45
4.22 7.71 11.20
-1.54 2.03 5.59
3.05 6.49 9.92
1.19 4.72 8.24
1.42 5.14 8.85
0.17 3.60 7.04
2.93 6.50 10.06
-1.71 1.73 5.17
1.19 4.72 8.24
2.19 5.67 9.16
4.37 7.85 11.33
1.71 5.19 8.66
2.29 5.73 9.17
4.37 7.85 11.33
-1.75 1.85 5.45
-1.17 2.43 6.03
2.24 6.23 10.22
3.05 6.49 9.92
0.17 3.60 7.04
2.38 5.87 9.36
-1.87 1.59 5.05
2.92 6.36 9.81
3.03 6.48 9.93
-2.94 0.68 4.30
2.92 6.36 9.81
2.92 6.36 9.81
0.41 4.39 8.37
2.73 6.16 9.60
0.76 4.54 8.32
1.81 5.27 8.74
3.60 7.03 10.46
3.60 7.03 10.46
3.93 7.57 11.22
1.37 4.81 8.25
0.76 4.54 8.32
2.13 5.57 9.01
0.41 3.92 7.42
0.17 3.60 7.04
2.35 5.78 9.20
3.05 6.71 10.36
-2.94 0.68 4.30
-1.79 1.86 5.51
1.19 4.72 8.24
2.58 6.16 9.74
3.03 6.48 9.93
2.35 5.78 9.20
2.19 5.67 9.16
4.37 7.85 11.33
3.03 6.48 9.93
4.55 8.21 11.87
1.84 5.56 9.28
4.13 7.57 11.01
-1.89 1.68 5.26
-1.36 2.44 6.24
2.34 5.79 9.23
3.61 7.08 10.55
1.84 5.49 9.14
-2.40 1.17 4.75
2.92 6.36 9.81
-1.87 1.59 5.05
-0.81 2.85 6.50
-1.91 1.57 5.06
2.45 5.90 9.35
1.14 4.71 8.2